name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama por defecto

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Ruby y Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Cambia esto según la versión de Ruby que necesites
          bundler-cache: true

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      # Paso 4: Construir el sitio
      - name: Build the site
        run: |
          bundle exec jekyll build

      # Paso 5: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directorio donde Jekyll genera los archivos HTML
